# Overlays merged on top of common.yaml for arx_lift.

ocs2_wbc_controller:
  ros__parameters:
    home_3: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    home_4: [0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

body_joint_controller:
  ros__parameters:
    home_3: [0.0]
    home_4: [0.15]

head_joint_controller:
  ros__parameters:
    home_3: [0.0, 0.0]
    home_4: [0.3, 0.0]
